import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
        <Head>
            <title>Home</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div>
            <h1>
                halaman home
            </h1>
            <p>add react gtm module</p>
        </div>
    </div>
  )
}
